### ISSUE TITLE
"|" characters inside a cell in Gsheet

### ISSUE THREAD

**Issue by fernhtls** [pffy/googledocs-addon-markdowntablefive#11]
Hi,

I've been using the add-on and it's working great for the major times we need to convert our spreadsheets to markdown, but I had some problems when rendering tables with "|" (pipe) characters inside a cell. I've got your code and I've changed it to include a escape character "\" together with the pipe character. Here's the snippet of the code. As I understand this is a fundamental problem when generating the markdown, I thought that would be good to include it in the add-on source code.

Here's the code that I've include in my version from line 208:

```javascript
          // for strings, converts carriage returns and newlines to BR html tag
          if(typeof currentValue === 'string') {
            currentValue = currentValue.replace((new RegExp('\\r', 'g')), '<br/>');
            currentValue = currentValue.replace((new RegExp('\\n', 'g')), '<br/>');
            // *********************** CHANGE ******************
            // AUTHOR: FERNANDO SOUZA - fernandohen
            // DATE: 14/12/2015
            // DESCRIPTION: INCLUDED NEW LINE BELOW.
            // INCLUDING AN ESCAPE CHARACTER WHEN THERE IS A "|"
            // IN THE REAL CONTENT FOR A CELL
            // *********************** CHANGE ******************
            currentValue = currentValue.replace(/\|/g, "\\|");
          }
```

Regards,

Fernando Souza

**Comment by pffy** [comment]
@fernhtls the feature request is accepted. 

Unfortunately, the code you sent fails in all markdown rendering engines, including GitHub. It is a "best practice" to NOT "render" the pipe in markdown tables because they are delimiters per the Markdown specification.

The compromise that will not break valid Markdown is to place the vertical pipe in `<code></code>` tags.

Here are solutions already discussed and deployed by others:
  + http://stackoverflow.com/a/17320389 (we implemented this code solution)
  + https://github.com/gitlabhq/gitlabhq/issues/1238
  + http://stackoverflow.com/a/28438027

**Comment by pffy** [comment]
fixed here. https://github.com/pffy/googlescript-markdowntablefive/issues/4
--QA
